language: go

go:
  - "1.9"
  - "1.10"

services:
  - memcached

before_install:
  - go get -t -v ./...

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
  - secure: AV/sFUQ3gMtXLr9H1mKznpAzJDFbpLTFjNgf9ATZDAlIHqD9aSq8PyudGl1JcALBXA3pmI/b6DKoCmwghd6Je90R6MyswJhJJUvs5UMKi1SntlPrzCRZjP7NM8prmY2jNWHuUTGJ5uRb6pfvQuKsRdmcO48DDLJR6WJxZBo3qrBRHdpxMoMOISzzqNABk2UFwHIJne9tGORl58bT5djPVDN9S+G/q/slox5W19e10u1g3gdpM7Cuuxzo/KMXbOAsQ/p+BaEjorQKFHtbyWqYDa0KKuD1orr3McbdjMkUh/5hA/WN0Vmig2V8wwPRRlj4JksA7HEECsvi9eWKaGF7qzOjW3OpbzpcrE4Uwl1AUiLyJA2duxWWS4ER5iorYNU1IR8ssHuyo7R/rrN6ajcoV7xQZ2Axxi5EwKX8swUsZTxH4S3zt4RbkaMeglQ6kT5ytKH7RTBx1BG9ctOWxxcsnc7n4Gea6N42Hfr1aeTqo3JNRxffuovyQtVKC3UuYTspV/Q1oa8KBaYvOuMXYAcCwSULSIm7gzJKmaT7S/idAMrCY4PojIbwC6/74PgdnJUTSGBs8It4QZKxbhTWg5f8LAiFtjbVS3VD5iBhf4L8brZfn+FPq/+1TApTLpYKLFvtcdV8/M6cP4gkvZ5pfQ1yODJz18fXSKnR2/PuTfhYcdI=
  - secure: gQfktUna0cjN2bSJGsGTo2C+BMnXAaCe4bNs7aC5Rny01sujmMT27VDt4zSWdUJoyuKv8qos1t8ccAnYfzRx29mua5e/wHLEsH7cQqBOcDKMf0lPAauYlYZCYH/B9nrqYOVuAxAWPQ+FRAuvmWoriWsMvCNMiS10fDMNZwR2mNzbY6zk0kHb/+zTC+hwUK7hIEdjqH2NULY5C3qrQ46iGjnjMo0I8waXwNllJlauJ07U3ApEYHBF2zPKEgyznAKIkxLnbHl86Xj2Sp/OhkSuZVmMJ1XNK/4Ulk7vcKrI9oVWwcy4Z0MAfU4COcGCBhy7uPaekXp/Ocpwk2ZpI2padgXNvkjxjXYRXvbOrr7ta9FQxlsCvPyWYh71TxUFORUn5fbVumdKmaUYXnPcPYhP4OQzVxtTP+8uYUBHyTbSWBcPksqJeca1IROOfB8pDCXDEFOhptHJICDG6xQmvktt0LcxP6jhJFq0zWgy3kxNjUbcVBaRxJ3xpj8vQIoahcrwjf4U/a5/74LLeiisOrgBtEI/9uuPQI/O9oXLnDsjuIUhvzay07APk/nLJeMjr/7XO2pusSKRxO4kvA41UU12JdgauckX6arWk3OId5TVNWKvIGXljeAahRQ/r91nPsmshEHPr4rLQLyo92AUFedzy7fJkIaArOx2yEp92gLvAuw=
  - secure: c9I+FrOTiIgjF3fyKqAHu8frr2POV0ed9RXPCujpjxRC3aP5ErZFXsPE8BDIylLDNULTOp92JsdwH/LXFlmSlWKxip/IKM6w5G9rx9M12t1TF8tuw5oTx/5N63odoEc9qJBH4lbH+8i1UHCsFTh5JoKRcQi8n5aI4WqCCSWS2YJFa1egXofAC7LIP+I3SDS3i+5SusFmy/ZyqE29ihUuDJa3S4Ru8N/WQaqfBXf/5VAHp9E9hk403bsJ73OK0H4bUsrnL4INYAVkACd9eubNNH5HWqhGsYvW/TIl4HXLKyPaTD3YVyKGXAzb5B/no6JnIELNNb8gVvUsAXcojJk84LckvSzaOmP5GWqap24XfA14/nZ3CBb9hCU8oIsWXbKtim1ObKF69EKCf3wP0/6XF7eZ/aGpLQPrtGoG849+/BxKm/OAi3y8V8ipwdhlOJZf/Enq+sQQZ/ZLycVbkxdNEos6fqiVCe0dNYgPz6DLMoTO1/NqXk7JYu8YQ6QgOrXOXJ6ae6YljLnZDxL1KTg0Z795I7Sy13uk/Wmmq63dZKhojXrd3yIUeclVUh90sZ20I2lCjY//lNRqY4eAhTRtrHJVV+CP80lgLy2qUO6GKfGnrIkLHvB7B74vAu4Eexyru5dDbiUdFOxDKD/VqXfunKe9g0wP2nM3OS6TCD3gJxI=
